language: python

python:
    - "2.7"

install:
    - pip install -e .
    - pip install mock coverage coveralls flake8
    # gui tests requirements
    # start xvfb to emulate a graphical session
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    # install Pyside from a wheel, this will speedup the tests as PySide
    # won't need to be compiled
    - sudo apt-get install libqt4-dev
    - pip install PySide --no-index --find-links https://parkin.github.io/python-wheelhouse/
    - pyside_postinstall.py -install

    - cd gui && pip install -r test-requirements.txt && cd ..

before_script:
    flake8 mozregression tests setup.py

script:
    - coverage run setup.py test
    - cd gui && python build.py test && cd ..

after_success:
    coveralls
