language: python

python:
    - "2.7"

install:
    pip install mock coverage coveralls flake8

before_script:
    flake8 mozregression tests setup.py

script:
    coverage run setup.py test

after_success:
    coveralls
