language: python

python:
    - "2.7"
virtualenv:
    # required because we install the python-qt4 ubuntu package
    system_site_packages: true

install:
    # gui tests requirements
    # start xvfb to emulate a graphical session
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    # install PyQt4
    - sudo apt-get install python-qt4 pyqt4-dev-tools
    # install mozregression code and test dependencies
    - pip install coverage coveralls
    - cd gui && pip install -r test-requirements.txt && cd ..

before_script:
    flake8 mozregression tests setup.py

script:
    - coverage run setup.py test
    - cd gui && coverage run build.py test && cd ..
    # now combine the coverage data
    - mv .coverage .coverage.core
    - mv gui/.coverage .coverage.gui
    - coverage combine

after_success:
    coveralls

before_deploy:
    - pip install cx_Freeze
    - cd gui
    - python build.py rcc
    - python build.py uic
    - cxfreeze --include-path=".:..:/usr/lib/python2.7:/usr/lib/python2.7/dist-packages" --target-name=mozregression-gui --target-dir=dist mozregui/main.py
    - tar -czf mozregression-gui.tar.gz dist/
    - cd ..

deploy:
    provider: releases
    api_key:
        secure: cBPLQbwYrV3+V1W+wE+iMftda1sTTEJaxjd2l6mt4yIVO95fTcLRv4ekq0UkpXAi4bk1CKguIz8w9v/9jAg9y4zyDamLM81iTJQYu4N9EdODWVcCBA4lNud+51XQcNvO/R2/6///TlZ1RUG5YzvwxyUlomsVdl+yvpX4OSrEik8=
    file: gui/mozregression-gui.tar.gz
    skip_cleanup: true
    on:
        tags: true
