build: false
environment:
  NSIS_ROOT: C:\nsis
  matrix:
    - PYTHON: "C:/Python27"
init:
  - "ECHO %PYTHON%"
  - "ECHO %PATH%"
install:
  - ps: (new-object net.webclient).DownloadFile('https://raw.github.com/pypa/pip/master/contrib/get-pip.py', 'C:/get-pip.py')
  - "%PYTHON%/python.exe C:/get-pip.py"
  # install PyQt4
  - cinst pyqt4 -y
  # install mozregression code and test dependencies
  - "cd gui & %PYTHON%/Scripts/pip.exe install -r test-requirements.txt"
  - "cd .."
test_script:
  - "%PYTHON%/python.exe setup.py test"
  - "cd gui"
  - "%PYTHON%/python.exe build.py test"
  - "cd .."
  # bundle the application
  - cinst nsis -y -installArgs /D=%NSIS_ROOT%
  - "%PYTHON%/Scripts/pip.exe install cx_Freeze"
  - "%PYTHON%/python.exe gui/build.py bundle"

# section required for deploy
artifacts:
  - path: gui\wininst\mozregression-gui.exe

deploy:
  - provider: GitHub
    auth_token:
      secure: 9JS0n1MfG2KVQ86suWQ7Zq51932EBanPp05GXoLfN+94AhMOQSerjUwGIxoBXKmp
    artifact: gui\wininst\mozregression-gui.exe
    on:
      appveyor_repo_tag: true
