# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/all.txt
        pip install -e .
    - name: Lint
      run: |
        ./bin/lint-check.sh || (echo "Lint fix results:" && ./bin/lint-fix.sh && git diff && false)
        bin/update-glean-documentation.sh
        if [[   $(git diff docs/glean | head -c1 | wc -c) -ne 0 ]]; then echo "Unexpected glean changes! Please regenerate glean documentation via `./bin/update-glean-documentation.sh`." && false; fi
    - name: Build
      run: |
        python gui/build.py bundle
        ls -alh gui/mozregression-gui.tar.gz
    - name: Test
      run: |
        sudo apt-get install x11-utils libxkbcommon-x11-0
        pip install pytest-xvfb
        export QT_DEBUG_PLUGINS=1
        pytest -v gui/tests
        #coverage run -m pytest tests && mv .coverage .coverage.core
        #coverage run gui/build.py test && mv .coverage .coverage.gui
        #coverage combine
        #pip install coveralls; coveralls
